[tool.poetry]
name = "2024"
version = "0.1.0"
description = ""
authors = ["Zech Zimmerman <hi@zech.codes>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
